name: Build | Tests | Coverage
on:
  pull_request:
    branches:    
      - main
      - stage
      
env:
  dotnet_version: 5.0.x

jobs:
  workflow:
    uses: AbarePizzarias/GithubWorkflows/.github/workflows/code_build.yml@main
    with:
      dotnet_version: ${{ env.dotnet_version }}
    secrets:
      code_analisys_api_token: ${{ secrets.CODACY_TOKEN }}