name: Push Package
on:
  push:
    branches:    
      - main

env:
  dotnet_version: 5.0.x
  project_path: src/xxxx

jobs:
  workflow:
    uses: AbarePizzarias/GithubWorkflows/.github/workflows/push_package.yml@main
    with:
      project_path: ${{ env.project_path }}
      dotnet_version: ${{ env.dotnet_version }}
    secrets:
      nuget_token: ${{ secrets.ECR_REGISTRY }}