name: Staging Deploy
on:
  push:
    branches:    
      - stage

jobs:
  workflow:
    uses: AbarePizzarias/GithubWorkflows/.github/workflows/staging_deploy.yml@main
    with:
      application_name: xxxxxxxx
      db_migrations_path: src/xxxxx
      project_context: xxxx
      dotnet_version: 5.0.x
    secrets:
      ecr_registry: ${{ secrets.ECR_REGISTRY }}
      aws_client_id: ${{ secrets.AWS_CLIENT_ID }}
      aws_client_secret: ${{ secrets.AWS_CLIENT_SECRET }}
      aws_region: ${{ secrets.AWS_REGION }}
      eks_cluster_name: ${{ secrets.EKS_CLUSTER_NAME }}
      helm_chart_name: ${{ secrets.API_HELM_CHART_NAME }}
      helm_chart_version: ${{ secrets.API_HELM_CHART_VERSION }}