name: Staging Deploy
on:
  push:
    branches:    
      - stage

env:
  dotnet_version: 5.0.x
  project_context: xxxx
  application_name: xxxxx
  db_migrations_path: src/xxxxx

jobs:

  workflow:
    uses: AbarePizzarias/GithubWorkflows/.github/workflows/staging_deploy.yml@main
    with:
      dotnet_version: ${{ env.dotnet_version }}
      project_context: ${{ env.project_context }}
      application_name: ${{ env.application_name }}
      db_migrations_path: ${{ env.db_migrations_path }}
    secrets:
      ecr_registry: ${{ secrets.ECR_REGISTRY }}
      aws_client_id: ${{ secrets.AWS_CLIENT_ID }}
      aws_client_secret: ${{ secrets.AWS_CLIENT_SECRET }}
      aws_region: ${{ secrets.AWS_REGION }}
      eks_cluster_name: ${{ secrets.EKS_CLUSTER_NAME }}
      helm_chart_name: ${{ secrets.API_HELM_CHART_NAME }}
      helm_chart_version: ${{ secrets.API_HELM_CHART_VERSION }}