name: Build | Tests | Coverage

on: 
  workflow_call:

    inputs:
      dotnet_version:
        required: true
        type: string
        
    secrets:
      code_analisys_api_token:
        required: true

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
          
      - name: Test with the dotnet CLI
        id: test_coverage
        env:
          ASPNETCORE_ENVIRONMENT: Development
        run: |
          dotnet test /p:CollectCoverage=true /p:CoverletOutput=../coverage /p:CoverletOutputFormat=opencover
          echo ::set-output name=coverage_file::$(echo $(find . -name "coverage.opencover.xml"))
        
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.code_analisys_api_token }}
          coverage-reports: ${{ steps.test_coverage.outputs.coverage_file }}
