name: Teste

on: 
  workflow_call:
    inputs:
      
      application_name:
        required: true
        type: string
      project_context:
        required: true
        type: string
      db_migrations_path:
        required: true
        type: string

    secrets:
      ecr_registry:
        required: true
      aws_client_id:
        required: true
      aws_client_secret:
        required: true
      aws_region:
        required: true
      eks_cluster_name:
        required: true
      helm_chart_name:
        required: true
      helm_chart_version:
        required: true
        
jobs:

  jobson:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo version ${{ secrets.helm_chart_version }}
