name: Push Package

on: 
  workflow_call:

    inputs:
      project_path:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string

    secrets:
      nuget_token:
        required: true

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Create package
        run: dotnet pack ${{ inputs.project_path }} --configuration Release

      - name: Publish package
        run: dotnet nuget push ${{ inputs.project_path }}/bin/Release/*.nupkg -k ${{ secrets.nuget_token }} -s "github" --skip-duplicate
